### ISSUE TITLE
all <li> tags "polutted" with '≫' globally

### ISSUE THREAD

**Issue by amir-arad** [arwes/arwes#110]
## Describe the bug

when I render arwes, all \<li\> nodes in the document get an `li:::before` node with content '≫'.

## To reproduce
render arwes in a DOM tree containing lists

## Expected behavior

don't affect  DOM elements outside arwes

- Packages version: 1.0.0-alpha.18
- Node.js 15.11 NPM 7.7.6
- OS: windows

## Testing environment
chrome latest on windows

**Comment by romelperez** [comment]
Hi @amir-arad !

The [`StylesBaseline`](https://playground.arwes.dev/core/StylesBaseline/basic) component adds global styles like this.

For now it is using `::before` but we can fix it with [`::marker`](https://developer.mozilla.org/en-US/docs/Web/CSS/::marker) pseudoselector.

If you are open to contribute with a PR, let me know and I can provide some instructions since currently there are no documentation for it.

**Comment by amir-arad** [comment]
I can try... CSS is not my strong suit but I've been around it enough.

I expect some standard solution like using an ancestor selector for all the styles ...?
Either that or some other component-friendly CSS solution?

**Comment by romelperez** [comment]
If it is changed to ::marker, it is the browser standard so it can be easily disabled with the CSS rule `list-style: none;`. Since the idea is to allow to style global (and in the future, scoped) HTML elements without custom components. There is also a `List` component but it is made for animations.

> I can try... CSS is not my strong suit but I've been around it enough.

Since there are no proper contributions instructions, don't worry, I can fix it for next release :wink:

**Comment by amir-arad** [comment]
I see similar problem with `line-height:30px` for all inputs. it should be all scoped IMO

**Comment by romelperez** [comment]
@amir-arad , the form elements will be covered later in the roadmap. So yes, there are many details and components to create about that. Thank you for reporting them :wink:

**Comment by romelperez** [comment]
Fixed in https://github.com/arwes/arwes/commit/9d480a3d1f9a8c0629ff8c05a59401e2a000b1a0.

Input/Textarea components will be handled in #112.
