### ISSUE TITLE
Research sound formats support for loop playing

### ISSUE THREAD

**Issue by romelperez** [arwes/arwes#22]
Some sounds are used in a loop. For example, the "typing/writing" sound which is played when the text is being "created/transitionedIn/appeared", is repeated over and over again until the text is completely shown.

Example: https://github.com/arwes/arwes/blob/main/playground/static/sounds/typing.mp3

MP3 files have a problem. They add extra time in the beginning and at the end of the audio on Chrome. Apparently, in Firefox this does not occur. Since the audio is on loop, the sound is played, paused for a few milliseconds, and then restarted, even if the sound can be really played in a loop.

Research has to be done to find a new file format supported by major browsers or a workaround to play sound effects without side-effects like that one.

For browser compatibility, see: https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats

- [x] Research sound file formats for sound effects without side-effects for loop playing.
- [x] Document your findings on this ticket.
- [x] Check if loop playback is now supported in [howlerjs.com](https://howlerjs.com) or what we need to make it work.

**Comment by njwest** [comment]
From my initial research, it appears that this problem is not unique to MP3s, but is rather a quirk of the HTML5 audio API.

Previously, devs achieved gapless playback with [Flash](https://stackoverflow.com/questions/4074790/how-to-loop-an-mp3-in-a-browser-with-zero-gap); obviously that isn't a viable solution since Flash is dead. 

Popular lib solutions include libs like [SoundManager](http://www.schillmania.com/projects/soundmanager2/). SoundManager used to be Flash-based, but now uses Flash as a fallback... 

This [Gapless Looping in HTML5](https://stackoverflow.com/questions/7330023/gapless-looping-audio-html5) SO thread contains the following solution, last edited Feb 2020:
Solution author:
"This solution worked for me. Experiment with the buffer to find out what works best for you"

```javascript
var audio_file = new Audio('whatever.mp3')
audio_file.addEventListener('timeupdate', function(){
    var buffer = .44
    if(this.currentTime > this.duration - buffer){
        this.currentTime = 0
        this.play()
    }
});
```

**Comment by njwest** [comment]
Also, here is the latest doc for [AudioBufferSourceNode > Looping](https://webaudio.github.io/web-audio-api/#looping-AudioBufferSourceNode) off of the [W3C Web Audio API](https://webaudio.github.io/web-audio-api/)

**Comment by romelperez** [comment]
Thank you @njwest !

Then create/use the sounds for the project as MP3 file format, since it is the most supported one.

Now that we know the sound looping is possible to solve by accessing the audio API, we can then define what tool/solution to use for this use case.

We can review if the original tool to manage sound playback, [howlerjs](https://howlerjs.com), now supports this kind of configuration, since it was presenting this issue initially. Otherwise, we can check a new approach such as [Gapless](https://github.com/regosen/Gapless-5).

(There isn't a list of requirements yet for the sound playback library to know what we need before we choose though :sweat_smile: )

**Comment by romelperez** [comment]
The original tool [howlerjs](https://howlerjs.com) can be then used as the sound playback library but only with the Web Audio API and not with the HTML5 Audio API when sounds require loop.

Also, the recommendation is now to use `webm` audio format instead of MP3 for better quality in modern browsers where Arwes is intended to be used. If IE is required, then MP3 has to be used.

The new [sounds tooling API](https://github.com/arwes/arwes/issues/81) has been defined. There it defines how to use loop sounds.

Thank you @njwest for helping out here :smile:
