### ISSUE TITLE
add modal and input components 

### ISSUE THREAD

**Issue by bpmutter** [arwes/arwes#46]
### add modal and input components to arwes framework

hi, i was recently making a project using the arwes framework and i created some input and modal components that i think could be added to the main framework with a bit of refactoring (which i'm happy to make and pull in). i think these additions could help turn arwes into a more full-feature UI framework, suitable for webapps.

i've attached a picture of the components in action below. are you interested in these additions?  

the project (star wars startrader application 🤓) can be found here: https://startrader-app.herokuapp.com/
with the frontend source code here: https://github.com/bpmutter/startrader

if you don't want to add to the core package here, i'll go ahead and make some separate arwes-modal / arwes-forms packages.

cheers, 
Ben Perlmutter 

p.s. tambien estoy basado en Medellin 🇨🇴

<img width="922" alt="modal and input example" src="https://user-images.githubusercontent.com/57849986/88836453-50dd3880-d19c-11ea-8590-739fbf32d93e.png">

**Comment by romelperez** [comment]
Hi Ben! That looks awesome! :smile: 

Since last year I have been delaying the development of the project due to personal reasons. I plan to resume it soon. The idea is to refactor the project framework, so the current architecture will not work anymore. I'll take your project as inspiration and if you are up to contribute by then, it'll be nice!

Genial que estés en Medellín! Esperando a que se estabilice el mundo para disfrutar de la ciudad otra vez :sweat_smile:

**Comment by bpmutter** [comment]
Gracias man! 

I’d love to contribute. In addition to the components themself, I like to write the technical docs (I’m weird like that), so I’d be happy to help with that too if you’d like. 

Otro idea que tenía para hacer el framework mas bacano es incluir varios modos de colores que se puede implementar fácilmente. (Kind of like the lightsaber color-based theming i put in the StarTrader site, but maybe even more robust). Lo veo como light y dark mode que se encuentra en muchos sitios estos días, pero mas sci-fi obvi. Sería bastante fácil hacer con tools como https://material.io/inline-tools/color/ <https://material.io/inline-tools/color/> (lo que usé por StarTrader). 

Y lamentablemente me voy de Medellin por los EEUU en septiembre pero espero regresar cuando podamos salir de casa de nuevo.

Cheers,
Ben

**Comment by kangalioo** [comment]
I don't wanna come across as a jerk but it would be nice if the conversations could be held in English or translated to English so they're accessible to more people

**Comment by jeffrey-cripe** [comment]
> I don't wanna come across as a jerk but it would be nice if the conversations could be held in English or translated to English so they're accessible to more people 

It's not like it's 2020, you could have taken the energy to copy/paste into google translate. Let people talk in whatever language they want...

**Comment by peterjcarroll** [comment]
For those who don't know Spanish, bpmutter said:

> Otro idea que tenía para hacer el framework mas bacano es incluir varios modos de colores que se puede implementar fácilmente.

Another idea I had to make the framework cooler is to include several color modes that can be implemented easily.

> Lo veo como light y dark mode que se encuentra en muchos sitios estos días, pero mas sci-fi obvi. Sería bastante fácil hacer con tools como https://material.io/inline-tools/color/ <https://material.io/inline-tools/color/> (lo que usé por StarTrader).

I see it like light and dark mode that you find on many sites these days, but more sci-fi obviously. It would be rather easy to do with tools like https://material.io/inline-tools/color/ <https://material.io/inline-tools/color/> (which I used for StarTrader).

> Y lamentablemente me voy de Medellin por los EEUU en septiembre pero espero regresar cuando podamos salir de casa de nuevo.

And unfortunately I'm leaving Medellin for the US in September but I hope to return when we can leave the house again.

**Comment by romelperez** [comment]
Hi @kangalioo, yes, the idea is to use English for communications in the project context so it is more accessible. But since this is an open channel, there is no control over it and sometimes it can be easier :man_shrugging: 

@peterjcarroll, thank you!

**Comment by roman-rr** [comment]
I definitely like this framework. 
Please check if it's possible to include as some of component my modal sheets solution [cupertino-pane](https://github.com/roman-rr/cupertino-pane)

**Comment by romelperez** [comment]
Hi @roman-rr, nice! Yes, when the time comes, I'll check it out! Thank you for sharing!

**Comment by 1NF053C** [comment]
hi. do any of u want help with implementation?

**Comment by romelperez** [comment]
Hello! 👋 

After quite some time without updates on the topic of UI components, due to lack of time and increase in complexity, the scope of the project was reduced to not have "complete" built-in UI components. The framework would still provide some UI components such as frames and backgrounds for special effects.

Normally, most science fiction design system projects are very specific, and creating something flexible enough for users to configure and extend is practically impossible with the resources at this time.

So, modal and form components, for example, are out of scope, at least for version 1. What might be included is just optional basic UI global styles for such elements.

For now, Arwes is encouraged to be used along with other UI frameworks/libraries such as MUI, Tailwind, or Ant. Arwes would provide more low-to-medium level tools to build visual, motion, and audio effects on existing and new UI components with sugar-APIs for common patterns to simplify development for these types of user experiences, so it can be added to existing projects or for new ones with other UI libraries/frameworks.

Personally, it has been a journey for me to learn many skills and experiment many times, to know that it was not the way and start again after much effort, since the idea is to have something flexible, fast, and stable enough for production apps.

Thank you all for your interest and patience! 👽
