### ISSUE TITLE
Type Declarations

### ISSUE THREAD

**Issue by roryscot** [arwes/arwes#52]
Create type declarations module and install with `npm install @types/arwes`

**Comment by roryscot** [comment]
Awesome project, by the way. Really cool.

**Comment by romelperez** [comment]
Hi @roryscot, yes, I plan to add typing for TypeScript and ideally Flow in the following alpha releases. Stay tuned!

**Comment by Dessix** [comment]
This is currently blocking my usage; If there's work you can divide up, I'd rather contribute to updating this than duplicate effort writing my own typings.
Any chance you could divide it up into tasks I (and maybe others) could take a crack at?

**Comment by romelperez** [comment]
Hi @Dessix,

The plan is to refactor completely the current public alpha, and since the APIs are going to change, I don't think it's a good idea to add types for the time being.

Once there is a more stable API, I'll create the corresponding tasks for anyone who wants to contribute adding them can do so.

Thank you!

**Comment by romelperez** [comment]
The project build system has been migrated to TypeScript with #61.

Since the only package completed is `@arwes/animation`, it is the only one functional for now. You can check it out in the project playground by downloading the repository and running `npm run playground-watch`, until the website is fully set up.

More features are on the way :factory_worker:
