### ISSUE TITLE
Wrapper components not possible with arwes in Nextjs

### ISSUE THREAD

**Issue by ivanjeremic** [arwes/arwes#53]
Normally Providers like `ThemeProvider ` are used in wrappers so you don't need to use them in every component, in Nextjs such a wrapper is the ` _app.js` but using the arwes `ThemeProvider ` there to wrap around the whole app does not work, it is still not recognized in separate components when using `withStyles ` for example, it says `withStyles ` needs a `ThemeProvider` to be able to use it, I clearly have one in the `_app.js` wrapper.

**Comment by romelperez** [comment]
Hi @ivanjeremic !

I would like to know more about this issue. I plan to continue using the ThemeProvider from JSS in the project and I'll have to look up at this soon. The idea is to have a guide to use Arwes in Gatsby.js and Next.js.

The provider package being used is this: https://github.com/cssinjs/theming#themeprovider

Can you elaborate more on this issue, please?

I guess it is due to outdated dependencies but I need more details.

**Comment by KaeruCT** [comment]
In case this helps anyone, I was able to get arwes working with Gatsby.js by installing this plugin: https://www.gatsbyjs.com/plugins/gatsby-plugin-jss-provider/

**Comment by romelperez** [comment]
Hello! 👋  Since the framework is now not coupled to a UI styling solution, this issue is out of scope. If you have any issue with the latest releases, don't hesitate to join Discord or open any other issue.
