### ISSUE TITLE
Allow component as header for project

### ISSUE THREAD

**Issue by waghcwb** [arwes/arwes#72]
## Is your feature request related to a problem? Please describe
I want to add a header with icon to the `Project` component, but it only accepts text,

It would be great if we can pass a custom component to the `header` attribute at `Project` component.

Also, if we don't pass the `header` attribute, I think the header should not be rendered

## Describe the solution you'd like

```jsx
function MyCustomHeader() {
  return (
    <>
      <svg>...</svg>
      <span>My custom title</span>
    </>
  )
}

function App() {
  return (
    <Project header={MyCustomHeader} animate>
      ...
    </Project>
  )
}
```

**Comment by romelperez** [comment]
Hi @waghcwb !

Since the framework is being rebuilt, the current public components are now deprecated. But you can use them as they are.

In the following months, a new component for heading will be made. This is a good feature to add to it. Let's leave this issue open for traceability.

Thank you @waghcwb !

**Comment by waghcwb** [comment]
Nice to know @romelperez.

If anyone else need something similar to what I asked, this was my alternative solution:

```jsx
<Frame
  show={true}
  level={3}
  corners={4}
  layer={'primary'}
  animate
  hover
  noBackground
>
  <div style={{ padding: 20 }}>
    {props.children}
  </div>
</Frame>
```

**Comment by romelperez** [comment]
Closed due to https://github.com/arwes/arwes/issues/46#issuecomment-1639308400
